name: crazy_hk_channels
description: تطبيق CRAZY HK CHANNELS يعمل بدون إنترنت

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/logo.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
